services:
   application:
     build: "./"
     container_name: rappidu-monolito
     restart: always
     ports:
       - "8080:8080"
     depends_on:
       - database

   database:
     image: mysql:5.7
     container_name: mysql-container
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: jdi
       MYSQL_PASSWORD: 5@290E4f
     ports:
       - "3306:3306"
     expose:
       - "3306"
