services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rappidu
      MYSQL_PASSWORD: root
    volumes:
      - ./initial-database.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"

  application:
    build: "./"
    container_name: rappidu-monolito
    restart: always
    ports:
      - "8080:8080"
    depends_on:
     - database
    links:
      - database